export { default as LoginPage } from "./public/LoginPage";
export { default as BasedPage } from "./private/BasedPage";
export { default as BasedsPage } from "./private/BasedsPage";
export { default as Error404Page } from "./public/404Page";
export { default as HomePage } from "./public/HomePage";
export { default as RegisterPage } from "./public/RegisterPage";
export { default as ManagementPage } from "./private/ManagementPage";
export { default as ReportsPage } from "./private/ReportsPage";
export { default as UsersPage } from "./private/UsersPage";
