export {AppFooter} from "./App/AppFooter"
export {AppHeader} from "./App/AppHeader"
export {Container} from "./App/Container"
export {Fondo} from "./App/fondo"
export {Home} from "./App/Home"
export {RegisterForm} from "./RegisterForm"
export {Loader} from "./App/Loader"